version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install bottle pytest requests
      - run:
          name: Run tests
          command: |
            pytest test_app.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
